[package]
name = "cc-dropbox"
version = "0.1.0"
authors = ["malet <malet@gmx.at>"]

[dependencies]
hyper = "*"
url = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]

[lib]
name = "ccdropbox"
crate-type = ["dylib"]
